"""empty message

Revision ID: 419871e99949
Revises: 
Create Date: 2023-04-13 18:12:03.617284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419871e99949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('roles', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('useragent', sa.String(length=100), nullable=False),
    sa.Column('action', sa.Enum('login', 'logout', name='actiontype'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('histories')
    op.drop_table('users')
    # ### end Alembic commands ###
