"""empty message

Revision ID: 9069e1d17767
Revises: a007f943888e
Create Date: 2023-04-19 19:13:30.162572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9069e1d17767'
down_revision = 'a007f943888e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_device_type', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['id', 'user_device_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('histories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_device_type')

    # ### end Alembic commands ###
