"""empty message

Revision ID: e8793c5cd9b4
Revises: 9069e1d17767
Create Date: 2023-04-19 21:23:09.190957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e8793c5cd9b4'
down_revision = '9069e1d17767'
branch_labels = None
depends_on = None


def upgrade():
    age_groups = postgresql.ENUM('undefined', '0-17', '18-24', '25-34', '35-44', '45-64', '65+', name='age_groups')
    age_groups.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.Enum('undefined', '0-17', '18-24', '25-34', '35-44', '45-64', '65+', name='age_groups'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###
